version: "2.1"

commands:
  ensure_deps:
    description: "Restores dependency cache or installs if changed/missing"
    steps:
      - restore_cache:
          keys:
          - lein-dependencies-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - .m2
          key: lein-dependencies-{{ checksum "project.clj" }}

jobs:
  test:
    docker:
      - image: clojure:lein-alpine
    working_directory: ~/kag
    environment:
      LEIN_ROOT: true
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - ensure_deps
      - run: lein test
  lint:
    docker:
      - image: clojure:lein-alpine
    working_directory: ~/kag
    environment:
      LEIN_ROOT: true
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - ensure_deps
      - run: lein eastwood

workflows:
  just_test:
    jobs:
      - test
      - lint
