version: "2.1"

commands:
  ensure_deps:
    description: "Restores dependency cache or installs if changed/missing"
    steps:
      - restore_cache:
          keys:
          - lein-dependencies-{{ checksum "project.clj" }}
          - lein-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - .m2
          key: lein-dependencies-{{ checksum "project.clj" }}

jobs:
  test:
    docker:
      - image: clojure:lein-alpine
    working_directory: ~/kag
    environment:
      LEIN_ROOT: true
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - ensure_deps
      - run: lein test
  lint:
    docker:
      - image: clojure:lein-alpine
    working_directory: ~/kag
    environment:
      LEIN_ROOT: true
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - ensure_deps
      - run: lein eastwood
  # deploy:
  #   docker:
  #     - image: clojure:lein
  #   environment:
  #     DEPLOY_HOST: 68.183.233.111
  #     PROD_CONFIG: config.edn
  #     KITSUNE_FOLDER: /usr/local/kitsune/
  #   working_directory: ~/kitsune
  #   steps:
  #     - checkout
  #     - ensure_deps
  #     - run:
  #         name: "Compile jar"
  #         command: lein uberjar
  #     - run:
  #         name: Fix host authenticity
  #         command: |
  #           ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
  #     - add_ssh_keys:
  #         fingerprints: ["65:66:d8:7e:1e:69:ed:f9:62:5a:c1:f3:60:0a:0e:7c"]
  #     - run:
  #         name: "Copy jar to server"
  #         command: scp target/uberjar/kitsune.jar circleci@$DEPLOY_HOST:$KITSUNE_FOLDER
  #     - run:
  #         name: "Finally start the server"
  #         command: ssh circleci@$DEPLOY_HOST "cd $KITSUNE_FOLDER; pkill -2 java; sleep 2; java -Dconf=$PROD_CONFIG -jar kitsune.jar"
  #         background: true
  #     - run:
  #         name: "Keep connection open long enough to start the server"
  #         command: sleep 30

workflows:
  just_test:
    jobs:
      - test
      - lint
#  test_and_deploy:
#    jobs:
#      - test
#      - lint
#      - deploy:
#          requires:
#            - test
#            - lint
#          filters:
#            branches:
#              only: develop
